{% set name = "lumispy" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lumispy-{{ version }}.tar.gz
  sha256: 56f3eea191d1a2152c2f512ed7bf0e530a100fabe5906f189560f2747ecef78b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hyperspy-base >=1.5.2
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - lumispy
    - lumispy.components
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lumispy/lumispy
  summary: Luminescence spectroscopy data analysis with HyperSpy.
  dev_url: https://github.com/lumispy/lumispy
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericpre
    - jlaehne
    - jordiferrero
