{% set name = "lumispy" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lumispy-{{ version }}.tar.gz
  sha256: 97d33386f85a7cc946471e42f162077abec6cd305a89489531536bf171c96736

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
  run:
    - hyperspy-base >=1.7
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - lumispy
    - lumispy.components
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lumispy/lumispy
  summary: Luminescence spectroscopy data analysis with HyperSpy.
  dev_url: https://github.com/lumispy/lumispy
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericpre
    - jlaehne
    - jordiferrero
