{% set name = "lumispy" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lumispy-{{ version }}.tar.gz
  sha256: 7257a79d936127b40edc1897fac8d89e7a29e7db3b39d8f063392b0ac2e6e513

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - hyperspy-base >=1.7
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - lumispy
    - lumispy.components
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lumispy/lumispy
  summary: Luminescence spectroscopy data analysis with HyperSpy.
  dev_url: https://github.com/lumispy/lumispy
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericpre
    - jlaehne
    - jordiferrero
